services:
  - type: web
    name: berryl_cooks
    env: static
    branch: main
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /
        destination: /berryl_recipes.html
